### ISSUE TITLE
error: '[string "return ..."]:2: attempt to index field ''map'' (a nil value)'

### ISSUE THREAD

**Issue by YadrovSergey** [monopollly/tarantool-db-template#1]
Привет.

Скопирвал ваш код.
Но при вызове db.jobs.map['owner']  - как у вас в примере, выскакивает ошибка:

error: '[string "return ..."]:2: attempt to index field ''map'' (a nil value)'

**Comment by YadrovSergey** [comment]
В логах нашел такую ошибку: Start failed: Can't create or modify index 'primary' in space 'jobs': unknown field type

**Comment by YadrovSergey** [comment]
Если вызвать db = init(db) в консоли тарантула, то вылезет эта ошибка:

unix/:/var/run/tarantool/dev.tarantool.control> db = init(db)
---
- error: '/etc/tarantool/instances.enabled/dev.tarantool.lua:66: attempt to index
    a nil value'

**Comment by monopollly** [comment]
да, спасибо, сча поправлю

это из за primary индекса, он должен быть всегда первым, 
то есть первое поле всегда должно быть primary индексом
а в любых других полях которые входят в индекс должен быть указан тип...

вот пример составного индекса
в parts первым всегда идет первое поле, потом какое угодно

```lua
db.test = {
-- индексы
{ tag = 'id', type='unsigned', index = 'primary' , parts = {'id', 'hash'}, unique = true},
-- поля
{ tag = 'hash', type='unsigned' },
{ tag = 'tag'},
{ tag = 'item'}
}

db.tags = {
-- индексы
{ tag = 'id', type='string', index = 'primary', parts = {'id', 'tagid'}, unique = true},
-- поля
{ tag = 'tagid',   type='unsigned' }
}
```

как то так

**Comment by monopollly** [comment]
вообще странно, только что проверил прям вставил код с гитхаба
все нормально... запускается без ошибок
https://gyazo.com/33eb9f9c5d6dc172ccb05f01e80839c7

**Comment by YadrovSergey** [comment]
Спасибо за ответ. Чуть позже еще раз проверю. Наверноя где-то затупил

**Comment by monopollly** [comment]
сча я тут короче все улучшу;)
